meal = """{
    "data":{
    "extStoreId":"SJ77777",
    "zhifubao":0,
    "deliveryFee":0,
    "productPrice":167,
    "storeName":"互联宝地测试店",
    "userId":0,
    "orderNo":"220831172038088100",
    "vipPhone":"",
    "orderStatus":10,
    "payType":2,
    "pricePremiums":0,
    "userNote":"测试测试测试！！用于订单备餐！",
    "counts":3,
    "merchantPrice":169.6,
    "isStoreFirstOrder":false,
    "virtualRealIncome":"0.0",
    "discounts":[

    ],
    "distanceIncreaseFee":0,
    "orderDate":"2022-08-31 17:20:38",
    "appointmentTime":"2022-08-31 18:05:38",
    "peopleNum":0,
    "isNeedTableware":0,
    "commission":1.4,
    "book":0,
    "customerHotline":"13",
    "longitude":"121.39847",
    "latitude":"31.131163",
    "sendBySelf":false,
    "driveDistance":0,
    "discountTotalPrice":0,
    "sn":"3",
    "orderId":"749559194457370624",
    "isInvoice":false,
    "sendType":1,
    "mealFee":4,
    "thirdSn":"3",
    "weixin":0,
    "price":171,
    "storeId":51937,
    "baseLogisticsServiceFee":0,
    "timeIntervalMarkUpFee":0,
    "tablewareNote":"0",
    "realTimeProductPrice":167,
    "isBrandFirstOrder":false,
    "phone":"18877750001",
    "couponPrice":0,
    "sendTime":"2022-08-31 18:05:38",
    "address":"中庚漫游城",
    "isPayed":true,
    "brandId":979,
    "isThirdDistribute":false,
    "thirdPlatformBearPrice":0,
    "deliveryDisTotalPrice":0,
    "name":"test",
    "brandName":"乐乐茶",
    "orderChildType":0,
    "merchantBearPrice":0,
    "tablewareRecycling":false,
    "barCode":"Mlo2kkKXBu1",
    "invoiceType":0,
    "agentBearPrice":0,
    "extId":"20220983110552333",
    "fromType":21,
    "virtualCommission":"0",
    "products":[
        {
            "typeId":545175,
            "taxRate":"",
            "totalPrice":65,
            "weight":0,
            "realTimeTotalPrice":65,
            "isCountMealFee":false,
            "listRequirements":[
                {
                    "index":0,
                    "totalPrice":0,
                    "propertys":[
                        {
                            "items":[
                                {
                                    "index":0,
                                    "totalPrice":0,
                                    "mealFee":0,
                                    "uid":2439277,
                                    "weight":0,
                                    "itemProduct":{
                                        "extMappingType":0,
                                        "pid":0,
                                        "extId":"83910017"
                                    },
                                    "bizType":0,
                                    "isStandardType":true,
                                    "price":10,
                                    "editType":0,
                                    "name":"大甘露料料（只限冰饮）",
                                    "num":1,
                                    "nameTw":"",
                                    "mulMealFee":0,
                                    "materialCost":0,
                                    "part":0,
                                    "realTimePrice":6,
                                    "nameEn":"",
                                    "itemType":1
                                }
                            ],
                            "pid":633916,
                            "editType":0,
                            "type":0,
                            "propertyMemo":"addition"
                        },
                        {
                            "items":[
                                {
                                    "index":0,
                                    "totalPrice":0,
                                    "mealFee":0,
                                    "uid":2439266,
                                    "weight":0,
                                    "itemProduct":{
                                        "extMappingType":0,
                                        "pid":0,
                                        "extId":"81010007"
                                    },
                                    "bizType":0,
                                    "isStandardType":false,
                                    "price":30,
                                    "editType":0,
                                    "name":"草莓桃子酪酪",
                                    "num":1,
                                    "nameTw":"",
                                    "mulMealFee":0,
                                    "materialCost":0,
                                    "part":0,
                                    "realTimePrice":0,
                                    "nameEn":"",
                                    "itemType":3
                                }
                            ],
                            "pid":633911,
                            "editType":0,
                            "type":0,
                            "propertyMemo":"drink"
                        },
                        {
                            "items":[
                                {
                                    "index":0,
                                    "totalPrice":0,
                                    "mealFee":0,
                                    "uid":2439267,
                                    "weight":0,
                                    "itemProduct":{
                                        "extMappingType":0,
                                        "pid":0,
                                        "extId":"81010016"
                                    },
                                    "bizType":0,
                                    "isStandardType":false,
                                    "price":28,
                                    "editType":0,
                                    "name":"葡萄酪酪",
                                    "num":1,
                                    "nameTw":"",
                                    "mulMealFee":0,
                                    "materialCost":0,
                                    "part":0,
                                    "realTimePrice":0,
                                    "nameEn":"",
                                    "itemType":3
                                }
                            ],
                            "pid":633912,
                            "editType":0,
                            "type":0,
                            "propertyMemo":"drink"
                        },
                        {
                            "items":[
                                {
                                    "index":0,
                                    "totalPrice":0,
                                    "mealFee":0,
                                    "uid":2439268,
                                    "weight":0,
                                    "itemProduct":{
                                        "extMappingType":0,
                                        "pid":0,
                                        "extId":"2000_2001"
                                    },
                                    "bizType":0,
                                    "isStandardType":false,
                                    "price":0,
                                    "editType":0,
                                    "name":"芝士酪酪（默认）",
                                    "num":1,
                                    "nameTw":"",
                                    "mulMealFee":0,
                                    "materialCost":0,
                                    "part":0,
                                    "realTimePrice":0,
                                    "nameEn":"",
                                    "itemType":3
                                }
                            ],
                            "pid":633913,
                            "editType":0,
                            "type":0,
                            "propertyMemo":"property"
                        },
                        {
                            "items":[
                                {
                                    "index":0,
                                    "totalPrice":0,
                                    "mealFee":0,
                                    "uid":2439270,
                                    "weight":0,
                                    "itemProduct":{
                                        "extMappingType":0,
                                        "pid":0,
                                        "extId":"1000_1009"
                                    },
                                    "bizType":0,
                                    "isStandardType":false,
                                    "price":0,
                                    "editType":0,
                                    "name":"冰沙（正常冰）",
                                    "num":1,
                                    "nameTw":"",
                                    "mulMealFee":0,
                                    "materialCost":0,
                                    "part":0,
                                    "realTimePrice":0,
                                    "nameEn":"",
                                    "itemType":3
                                }
                            ],
                            "pid":633914,
                            "editType":0,
                            "type":0,
                            "propertyMemo":"property"
                        },
                        {
                            "items":[
                                {
                                    "index":0,
                                    "totalPrice":0,
                                    "mealFee":0,
                                    "uid":2439274,
                                    "weight":0,
                                    "itemProduct":{
                                        "extMappingType":0,
                                        "pid":0,
                                        "extId":"4000_4001"
                                    },
                                    "bizType":0,
                                    "isStandardType":false,
                                    "price":0,
                                    "editType":0,
                                    "name":"冰糖（默认）",
                                    "num":1,
                                    "nameTw":"",
                                    "mulMealFee":0,
                                    "materialCost":0,
                                    "part":0,
                                    "realTimePrice":0,
                                    "nameEn":"",
                                    "itemType":3
                                }
                            ],
                            "pid":633915,
                            "editType":0,
                            "type":0,
                            "propertyMemo":"property"
                        }
                    ],
                    "requirementTotalMealFee":0,
                    "editType":0,
                    "price":0,
                    "realTimeTotalPrice":0,
                    "listRequirementWeight":0,
                    "listRequirementMaterialCost":0,
                    "num":1,
                    "originalPrice":0,
                    "total":0,
                    "originalTotal":0
                }
            ],
            "num":1,
            "aliasName":"",
            "mulMealFee":0,
            "materialCost":0,
            "groupMealFeeMode":0,
            "nameEn":"",
            "total":0,
            "propertyId":0,
            "bagNo":"1号篮子",
            "realTimePrice":59,
            "mealFee":2,
            "totalMealFee":2,
            "cartDataIndex":0,
            "originTotalMealFee":0,
            "choiceDiscountType":0,
            "productTags":[

            ],
            "parentTypeId":0,
            "costSinglePrice":59,
            "costPrice":0,
            "isFtpProduct":false,
            "isPreProduct":false,
            "isHBW":false,
            "name":"双杯饮品+加料-测试",
            "pid":1545941,
            "price":59,
            "materialMode":0,
            "part":0,
            "propertyMealFeeMode":false,
            "originalPrice":0,
            "weightDimension":1,
            "boxNum":1,
            "isAddedPreProduct":false,
            "originalTotal":0,
            "boxPrice":0,
            "productNo":1,
            "isSongPreProduct":false,
            "editType":0,
            "extId":"81010007",
            "tagUid":0,
            "aliasNameEn":"",
            "aliasNameTw":"",
            "nameTw":"Set",
            "isRecommend":false,
            "taxCategoryCode":""
        },
        {
            "typeId":545175,
            "taxRate":"",
            "totalPrice":69,
            "weight":0,
            "realTimeTotalPrice":69,
            "isCountMealFee":false,
            "listRequirements":[
                {
                    "index":0,
                    "totalPrice":0,
                    "propertys":[
                        {
                            "items":[
                                {
                                    "index":0,
                                    "totalPrice":0,
                                    "mealFee":0,
                                    "uid":2439278,
                                    "weight":0,
                                    "itemProduct":{
                                        "extMappingType":0,
                                        "pid":0,
                                        "extId":"83910046"
                                    },
                                    "bizType":0,
                                    "isStandardType":true,
                                    "price":11,
                                    "editType":0,
                                    "name":"双倍草莓",
                                    "num":1,
                                    "nameTw":"",
                                    "mulMealFee":0,
                                    "materialCost":0,
                                    "part":0,
                                    "realTimePrice":10,
                                    "nameEn":"",
                                    "itemType":1
                                }
                            ],
                            "pid":633916,
                            "editType":0,
                            "type":0,
                            "propertyMemo":"addition"
                        },
                        {
                            "items":[
                                {
                                    "index":0,
                                    "totalPrice":0,
                                    "mealFee":0,
                                    "uid":2439266,
                                    "weight":0,
                                    "itemProduct":{
                                        "extMappingType":0,
                                        "pid":0,
                                        "extId":"81010007"
                                    },
                                    "bizType":0,
                                    "isStandardType":false,
                                    "price":30,
                                    "editType":0,
                                    "name":"草莓桃子酪酪",
                                    "num":1,
                                    "nameTw":"",
                                    "mulMealFee":0,
                                    "materialCost":0,
                                    "part":0,
                                    "realTimePrice":0,
                                    "nameEn":"",
                                    "itemType":3
                                }
                            ],
                            "pid":633911,
                            "editType":0,
                            "type":0,
                            "propertyMemo":"drink"
                        },
                        {
                            "items":[
                                {
                                    "index":0,
                                    "totalPrice":0,
                                    "mealFee":0,
                                    "uid":2439267,
                                    "weight":0,
                                    "itemProduct":{
                                        "extMappingType":0,
                                        "pid":0,
                                        "extId":"81010016"
                                    },
                                    "bizType":0,
                                    "isStandardType":false,
                                    "price":28,
                                    "editType":0,
                                    "name":"葡萄酪酪",
                                    "num":1,
                                    "nameTw":"",
                                    "mulMealFee":0,
                                    "materialCost":0,
                                    "part":0,
                                    "realTimePrice":0,
                                    "nameEn":"",
                                    "itemType":3
                                }
                            ],
                            "pid":633912,
                            "editType":0,
                            "type":0,
                            "propertyMemo":"drink"
                        },
                        {
                            "items":[
                                {
                                    "index":0,
                                    "totalPrice":0,
                                    "mealFee":0,
                                    "uid":2439268,
                                    "weight":0,
                                    "itemProduct":{
                                        "extMappingType":0,
                                        "pid":0,
                                        "extId":"2000_2001"
                                    },
                                    "bizType":0,
                                    "isStandardType":false,
                                    "price":0,
                                    "editType":0,
                                    "name":"芝士酪酪（默认）",
                                    "num":1,
                                    "nameTw":"",
                                    "mulMealFee":0,
                                    "materialCost":0,
                                    "part":0,
                                    "realTimePrice":0,
                                    "nameEn":"",
                                    "itemType":3
                                }
                            ],
                            "pid":633913,
                            "editType":0,
                            "type":0,
                            "propertyMemo":"property"
                        },
                        {
                            "items":[
                                {
                                    "index":0,
                                    "totalPrice":0,
                                    "mealFee":0,
                                    "uid":2439270,
                                    "weight":0,
                                    "itemProduct":{
                                        "extMappingType":0,
                                        "pid":0,
                                        "extId":"1000_1009"
                                    },
                                    "bizType":0,
                                    "isStandardType":false,
                                    "price":0,
                                    "editType":0,
                                    "name":"冰沙（正常冰）",
                                    "num":1,
                                    "nameTw":"",
                                    "mulMealFee":0,
                                    "materialCost":0,
                                    "part":0,
                                    "realTimePrice":0,
                                    "nameEn":"",
                                    "itemType":3
                                }
                            ],
                            "pid":633914,
                            "editType":0,
                            "type":0,
                            "propertyMemo":"property"
                        },
                        {
                            "items":[
                                {
                                    "index":0,
                                    "totalPrice":0,
                                    "mealFee":0,
                                    "uid":2439274,
                                    "weight":0,
                                    "itemProduct":{
                                        "extMappingType":0,
                                        "pid":0,
                                        "extId":"4000_4001"
                                    },
                                    "bizType":0,
                                    "isStandardType":false,
                                    "price":0,
                                    "editType":0,
                                    "name":"冰糖（默认）",
                                    "num":1,
                                    "nameTw":"",
                                    "mulMealFee":0,
                                    "materialCost":0,
                                    "part":0,
                                    "realTimePrice":0,
                                    "nameEn":"",
                                    "itemType":3
                                }
                            ],
                            "pid":633915,
                            "editType":0,
                            "type":0,
                            "propertyMemo":"property"
                        }
                    ],
                    "requirementTotalMealFee":0,
                    "editType":0,
                    "price":0,
                    "realTimeTotalPrice":0,
                    "listRequirementWeight":0,
                    "listRequirementMaterialCost":0,
                    "num":1,
                    "originalPrice":0,
                    "total":0,
                    "originalTotal":0
                }
            ],
            "num":1,
            "aliasName":"",
            "mulMealFee":0,
            "materialCost":0,
            "groupMealFeeMode":0,
            "nameEn":"",
            "total":0,
            "propertyId":0,
            "bagNo":"1号篮子",
            "realTimePrice":59,
            "mealFee":2,
            "totalMealFee":2,
            "cartDataIndex":0,
            "originTotalMealFee":0,
            "choiceDiscountType":0,
            "productTags":[

            ],
            "parentTypeId":0,
            "costSinglePrice":59,
            "costPrice":0,
            "isFtpProduct":false,
            "isPreProduct":false,
            "isHBW":false,
            "name":"双杯饮品+加料-测试",
            "pid":1545941,
            "price":59,
            "materialMode":0,
            "part":0,
            "propertyMealFeeMode":false,
            "originalPrice":0,
            "weightDimension":1,
            "boxNum":1,
            "isAddedPreProduct":false,
            "originalTotal":0,
            "boxPrice":0,
            "productNo":2,
            "isSongPreProduct":false,
            "editType":0,
            "extId":"81010007",
            "tagUid":0,
            "aliasNameEn":"",
            "aliasNameTw":"",
            "nameTw":"Set",
            "isRecommend":false,
            "taxCategoryCode":""
        },
        {
            "typeId":0,
            "taxRate":"",
            "totalPrice":33,
            "weight":0,
            "realTimeTotalPrice":33,
            "isCountMealFee":false,
            "listRequirements":[
                {
                    "index":0,
                    "totalPrice":0,
                    "propertys":[
                        {
                            "items":[
                                {
                                    "index":0,
                                    "totalPrice":0,
                                    "mealFee":0,
                                    "uid":2439300,
                                    "weight":0,
                                    "itemProduct":{
                                        "extMappingType":0,
                                        "pid":0,
                                        "extId":"83910019"
                                    },
                                    "bizType":0,
                                    "isStandardType":true,
                                    "price":2,
                                    "editType":0,
                                    "name":"奥利奥料料",
                                    "num":1,
                                    "nameTw":"",
                                    "mulMealFee":0,
                                    "materialCost":0,
                                    "part":0,
                                    "realTimePrice":2,
                                    "nameEn":"",
                                    "itemType":1
                                }
                            ],
                            "pid":634248,
                            "editType":0,
                            "type":0,
                            "propertyMemo":""
                        },
                        {
                            "items":[
                                {
                                    "index":0,
                                    "totalPrice":0,
                                    "mealFee":0,
                                    "uid":2439305,
                                    "weight":0,
                                    "itemProduct":{
                                        "extMappingType":0,
                                        "pid":0,
                                        "extId":"1000_1001"
                                    },
                                    "bizType":0,
                                    "isStandardType":false,
                                    "price":0,
                                    "editType":0,
                                    "name":"正常冰",
                                    "num":1,
                                    "nameTw":"",
                                    "mulMealFee":0,
                                    "materialCost":0,
                                    "part":0,
                                    "realTimePrice":0,
                                    "nameEn":"",
                                    "itemType":3
                                }
                            ],
                            "pid":634249,
                            "editType":0,
                            "type":0,
                            "propertyMemo":""
                        },
                        {
                            "items":[
                                {
                                    "index":0,
                                    "totalPrice":0,
                                    "mealFee":0,
                                    "uid":2439310,
                                    "weight":0,
                                    "itemProduct":{
                                        "extMappingType":0,
                                        "pid":0,
                                        "extId":"4000_4001"
                                    },
                                    "bizType":0,
                                    "isStandardType":false,
                                    "price":0,
                                    "editType":0,
                                    "name":"冰糖",
                                    "num":1,
                                    "nameTw":"",
                                    "mulMealFee":0,
                                    "materialCost":0,
                                    "part":0,
                                    "realTimePrice":0,
                                    "nameEn":"",
                                    "itemType":3
                                }
                            ],
                            "pid":634250,
                            "editType":0,
                            "type":0,
                            "propertyMemo":""
                        },
                        {
                            "items":[
                                {
                                    "index":0,
                                    "totalPrice":0,
                                    "mealFee":0,
                                    "uid":2439314,
                                    "weight":0,
                                    "itemProduct":{
                                        "extMappingType":0,
                                        "pid":0,
                                        "extId":"2000_2001"
                                    },
                                    "bizType":0,
                                    "isStandardType":false,
                                    "price":0,
                                    "editType":0,
                                    "name":"芝士酪酪",
                                    "num":1,
                                    "nameTw":"",
                                    "mulMealFee":0,
                                    "materialCost":0,
                                    "part":0,
                                    "realTimePrice":0,
                                    "nameEn":"",
                                    "itemType":3
                                }
                            ],
                            "pid":634251,
                            "editType":0,
                            "type":0,
                            "propertyMemo":""
                        },
                        {
                            "items":[
                                {
                                    "index":0,
                                    "totalPrice":0,
                                    "mealFee":0,
                                    "uid":2439319,
                                    "weight":0,
                                    "itemProduct":{
                                        "extMappingType":0,
                                        "pid":0,
                                        "extId":"3000_3001"
                                    },
                                    "bizType":0,
                                    "isStandardType":false,
                                    "price":0,
                                    "editType":0,
                                    "name":"正常甜（推荐）",
                                    "num":1,
                                    "nameTw":"",
                                    "mulMealFee":0,
                                    "materialCost":0,
                                    "part":0,
                                    "realTimePrice":0,
                                    "nameEn":"",
                                    "itemType":3
                                }
                            ],
                            "pid":634252,
                            "editType":0,
                            "type":0,
                            "propertyMemo":""
                        },
                        {
                            "items":[
                                {
                                    "index":0,
                                    "totalPrice":0,
                                    "mealFee":0,
                                    "uid":2439323,
                                    "weight":0,
                                    "itemProduct":{
                                        "extMappingType":0,
                                        "pid":0,
                                        "extId":"6000_6001"
                                    },
                                    "bizType":0,
                                    "isStandardType":false,
                                    "price":0,
                                    "editType":0,
                                    "name":"翠芽",
                                    "num":1,
                                    "nameTw":"",
                                    "mulMealFee":0,
                                    "materialCost":0,
                                    "part":0,
                                    "realTimePrice":0,
                                    "nameEn":"",
                                    "itemType":3
                                }
                            ],
                            "pid":634253,
                            "editType":0,
                            "type":0,
                            "propertyMemo":""
                        },
                        {
                            "items":[
                                {
                                    "index":0,
                                    "totalPrice":0,
                                    "mealFee":0,
                                    "uid":2439329,
                                    "weight":0,
                                    "itemProduct":{
                                        "extMappingType":0,
                                        "pid":0,
                                        "extId":"1100_11001"
                                    },
                                    "bizType":0,
                                    "isStandardType":false,
                                    "price":0,
                                    "editType":0,
                                    "name":"冰",
                                    "num":1,
                                    "nameTw":"",
                                    "mulMealFee":0,
                                    "materialCost":0,
                                    "part":0,
                                    "realTimePrice":0,
                                    "nameEn":"",
                                    "itemType":3
                                }
                            ],
                            "pid":634254,
                            "editType":0,
                            "type":0,
                            "propertyMemo":""
                        }
                    ],
                    "requirementTotalMealFee":0,
                    "editType":0,
                    "price":0,
                    "realTimeTotalPrice":0,
                    "listRequirementWeight":0,
                    "listRequirementMaterialCost":0,
                    "num":1,
                    "originalPrice":0,
                    "total":0,
                    "originalTotal":0
                }
            ],
            "num":1,
            "aliasName":"",
            "mulMealFee":0,
            "materialCost":0,
            "groupMealFeeMode":0,
            "nameEn":"",
            "total":0,
            "propertyId":0,
            "bagNo":"1号篮子",
            "realTimePrice":31,
            "mealFee":0,
            "totalMealFee":0,
            "cartDataIndex":0,
            "originTotalMealFee":0,
            "choiceDiscountType":0,
            "productTags":[

            ],
            "parentTypeId":0,
            "costSinglePrice":31,
            "costPrice":0,
            "isFtpProduct":false,
            "isPreProduct":false,
            "isHBW":false,
            "name":"草莓桃子酪酪",
            "pid":1545953,
            "price":31,
            "materialMode":0,
            "part":0,
            "propertyMealFeeMode":false,
            "originalPrice":0,
            "weightDimension":1,
            "boxNum":1,
            "isAddedPreProduct":false,
            "originalTotal":0,
            "boxPrice":0,
            "productNo":3,
            "isSongPreProduct":false,
            "editType":0,
            "extId":"81010007",
            "tagUid":0,
            "aliasNameEn":"",
            "aliasNameTw":"",
            "nameTw":"",
            "isRecommend":false,
            "taxCategoryCode":""
        }
    ],
    "allowanceServiceFee":0,
    "propertyFollowMenu":false,
    "driverStatus":0,
    "totalWeight":0
},
    "sign": "cc011562953beb2145369"
}"""